version: '3.4'

services:
  sourcingdb: 
    container_name: sourcingdb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
       #- ./data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionStrings=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
       - sourcingdb
       - rabbitmq
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/

    ports:
      - "8000:80"
     
   
  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionStrings=mongodb://sourcingdb:27017"
    depends_on:
        - sourcingdb

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/

    ports:
      - "8001:80"
     
    
