version: '3.4'

services:
  sourcingdb: 
    container_name: sourcingdb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
       #- ./data:/data/db
    ports:
      - "27017:27017"


  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ProductDatabaseSettings:ConnectionStrings=mongodb://sourcingdb:27017"
    depends_on:
       - sourcingdb
    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/

    ports:
      - "8000:80"
     
   
  esourcing.sourcing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
